server:
  port: 5666

security:
  oauth2:
    client:
      client-id: cloud
      client-secret: 123456
    resource:
      jwt:
        key-value: 123456
#        key-uri: http://localhost:8123/oauth/token_key
spring:
  main:
    allow-bean-definition-overriding: true